#服务器配置
server:
  port: 8080
  servlet:
    context-path: /dynamic
#数据库相关配置
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/book_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT"
    username: root
    password: 86593772
    driver-class-name: com.mysql.cj.jdbc.Driver
    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    static-path-pattern: /**

#mybatis plus配置
mybatis-plus:
  #如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  #如果是放在resourse目录 classpath:/mapper/*Mapper.xml
  mapper-location: classpath*:mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lb.common.entity
  global-config:
    #主键类型
     id-type: 0
     field-starategy: 0
     logic-delete-value: 1
     logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-enums-package: com.st.dynamic.entity.enums